/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgFrame;

import pkgClass.clsArbol;
import pkgClass.clsNodo;

/**
 *
 * @author amartinez
 */
public class frmArbolBinario extends javax.swing.JFrame {
    clsArbol arbol;
    /**
     * Creates new form frmArbolBinario
     */
    public frmArbolBinario() {
        initComponents();
        this.arbol = new clsArbol(); // Pone root como null
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInsertar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        txtNum = new javax.swing.JTextField();
        btnBorradoGrupo1 = new javax.swing.JButton();
        btnBorradoGrupo2 = new javax.swing.JButton();
        btnBorradoGrupo3 = new javax.swing.JButton();
        btnBorradoGrupo4 = new javax.swing.JButton();
        btnBorradoGrupo5 = new javax.swing.JButton();
        lblRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnListar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });

        txtNum.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnBorradoGrupo1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBorradoGrupo1.setText("Borrado Grupo 1");
        btnBorradoGrupo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorradoGrupo1ActionPerformed(evt);
            }
        });

        btnBorradoGrupo2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBorradoGrupo2.setText("Borrado Grupo 2");

        btnBorradoGrupo3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBorradoGrupo3.setText("Borrado Grupo 3");

        btnBorradoGrupo4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBorradoGrupo4.setText("Borrado Grupo 4");

        btnBorradoGrupo5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBorradoGrupo5.setText("Borrado Grupo 5");
        btnBorradoGrupo5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorradoGrupo5ActionPerformed(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRespuesta.setText("s");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNum, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBorradoGrupo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorradoGrupo4))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnBorradoGrupo3)
                        .addGap(42, 42, 42)
                        .addComponent(lblRespuesta))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnListar, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBorradoGrupo2)
                                .addGap(22, 22, 22)
                                .addComponent(btnBorradoGrupo5)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar)
                    .addComponent(btnListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorradoGrupo1)
                    .addComponent(btnBorradoGrupo4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorradoGrupo2)
                    .addComponent(btnBorradoGrupo5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBorradoGrupo3)
                    .addComponent(lblRespuesta))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        this.arbol.insertar(new clsNodo(Integer.parseInt(txtNum.getText()), null, null)  , this.arbol.getRoot());
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        // TODO add your handling code here:
        this.arbol.listar(this.arbol.getRoot());
    }//GEN-LAST:event_btnListarActionPerformed

    private void btnBorradoGrupo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorradoGrupo1ActionPerformed
        
    }//GEN-LAST:event_btnBorradoGrupo1ActionPerformed

    private void btnBorradoGrupo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorradoGrupo5ActionPerformed
        // TODO add your handling code here:
        this.arbol.buscarElim(new clsNodo(Integer.parseInt(txtNum.getText()),null ,null), this.arbol.getRoot());
    }//GEN-LAST:event_btnBorradoGrupo5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArbolBinario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmArbolBinario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorradoGrupo1;
    private javax.swing.JButton btnBorradoGrupo2;
    private javax.swing.JButton btnBorradoGrupo3;
    private javax.swing.JButton btnBorradoGrupo4;
    private javax.swing.JButton btnBorradoGrupo5;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextField txtNum;
    // End of variables declaration//GEN-END:variables
}
